# Site settings
title: "Oral and Maxillofacial Surgery of Greeley PC"
email: "team@variantstudios.com"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/ - keep empty!
url: "https://useful-anteater.cloudvent.net" # the base hostname & protocol for your site - don't include the forward slash
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.8.2" # the version of jekyll

#CloudCannon defaults
uploads_dir: "assets/images"

# Gems for plugins
plugins:
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).
  - jekyll-include-cache # Cache jekyll includes to improve build times

# Permalinks
permalink: pretty

# Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: true
  startings: [html, head, body]

#Collections
collections:
  procedures:
    output: true
    permalink: '/procedures/:title/'

defaults:
  -
    scope:
      type: procedures
    values:
      layout: procedure
      class: procedures
      _options:
        image_path: # Front matter field
          uploads_dir: "assets/images/procedures/"
  -
    scope:
      type: categories
    values:
      layout: category
      class: blog
      pagination: 
        enabled: true
  
# Cloudcannon Options
_options:
  some_markdown:
    bold: true
    table: true
  _text:
    italic: true
  _block:
    # format: p h3
    # undo: true
    # redo: true
    left: align-to-left
    center: align-to-center
    right: align-to-right
  content:
    removeformat: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    numberedlist: true
    bulletedlist: true
    outdent: true
    indent: true
    table: true
    link: true
    image: true
    styles: /assets/css/wysiwyg.css
  share_image_path:
    width: 1200
    height: 1200
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: false
    uploads_dir: "assets/images/share"
    
_comments:
  share_image_path: "The social share image needs to be at least 1200x1200px and if not that exact same size CloudCannon will scale and crop it to 1200x1200."

# Cloudinary
# cloudinaryurl: 'https://res.cloudinary.com/grow-your-storage/'

# Typekit
# typekit: "dan8xfd"

# Google Analytics 
google_analytics_tracking_id:

include: ["_collections"]

exclude: [
  "siteicon.png",
  "npm-debug.log",
  "Gemfile",
  "Gemfile.lock",
  "README.md",
  "assets/**/*.md",
  "gulpfile.js",
  "node_modules",
  "npm-shrinkwrap.json",
  "package-lock.json",
  "package.json",
  "proofScripts.js",
  "*.map",
  "*.scss",
  "assets/js/dev"
  ]
