# Site settings
title: "Wisdom Ways Acupuncture"
email: "team@variantstudios.com"
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/ - keep empty!
url: "https://solitary-chinchilla.cloudvent.net" # the base hostname & protocol for your site - don't include the forward slash
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.8.2" # the version of jekyll

#CloudCannon defaults
uploads_dir: "assets/images"

# Gems for plugins
plugins:
 # - jekyll-paginate
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).
  - jekyll-include-cache # Cache jekyll includes to improve build times

#paginate: 5
#paginate_path: "/blog/page:num/"

# Permalinks
permalink: pretty

# Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: true
  startings: [html, head, body]

#Collections
collections:
  posts:
    output: true
    permalink: '/blog/:title/'
  categories:
    output: true
    _hide_content: true
    permalink: '/blog/category/:path/'
  tags:
    output: true
    _hide_content: true
    permalink: '/blog/tag/:path/'
  conditions:
    output: true
    permalink: '/conditions-treated/:title/'
  services:
    output: true
    permalink: '/services-offered/:title/'
  team:
    output: false

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      class: single post
      _options:
        image_path: # Front matter field
          uploads_dir: "assets/images/posts/"  
  -
    scope:
      type: conditions
    values:
      layout: conditions
      class: conditions
      _options:
        image_path: # Front matter field
          uploads_dir: "assets/images/conditions/"
  -
    scope:
      type: services
    values:
      layout: services
      class: services
      _options:
        image_path: # Front matter field
          uploads_dir: "assets/images/services/"
  -
    scope:
      type: team
    values:
      _options:
        image_path: # Front matter field
          uploads_dir: "assets/images/team/"
  -
    scope:
      type: categories
    values:
      layout: category
      class: blog
  -
    scope:
      type: tags
    values:
      layout: tags
      class: blog
        
# Cloudcannon Options
_options:
  _text:
    bold: true
    italic: true
    link: true
  _block:
    removeformat: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    numberedlist: true
    bulletedlist: true
    outdent: true
    indent: true
    table: true
    link: true
    image: true
    styles: /assets/css/wysiwyg.css
    embed: true
    left: align-to-left
    center: align-to-center
    right: align-to-right
  content:
    removeformat: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    numberedlist: true
    bulletedlist: true
    outdent: true
    indent: true
    table: true
    link: true
    image: true
    styles: /assets/css/wysiwyg.css
    embed: true
    left: align-to-left
    center: align-to-center
    right: align-to-right
  share_image_path:
    width: 1200
    height: 1200
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: false
    uploads_dir: "assets/images/share"
  hero_image:
    width: 1200
    height: 412
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: false
    uploads_dir: "assets/images/heroes"
    
_comments:
  share_image_path: "The social share image needs to be at least 1200x1200px and if not that exact same size CloudCannon will scale and crop it to 1200x1200."
  hero_image: "The hero image needs to be a jpeg and exactly 1200px wide by 412px tall and if not that exact same size CloudCannon will scale and crop it to 1200px wide."

#Cloudinary
cloudinaryurl: 'https://res.cloudinary.com/wisdomways/'

# Typekit
# typekit: "dan8xfd"

# Google Analytics 
google_analytics_tracking_id:

exclude: [
  "siteicon.png",
  "npm-debug.log",
  "Gemfile",
  "Gemfile.lock",
  "README.md",
  "assets/**/*.md",
  "gulpfile.js",
  "node_modules",
  "npm-shrinkwrap.json",
  "package-lock.json",
  "package.json",
  "proofScripts.js",
  "*.map",
  "*.scss",
  "assets/js/dev"
  ]
